version: "3"

services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    restart: always
#     volumes:
#       - database:/var/lib/postgresql/data
# volumes:
#   database:
#     driver: local
