name: Deploy Stage and run E2E

on:
  push:
    branches:
      - stage

jobs:
  # Do stuff to run unit tests?
  # With turbo, I'll probably do this in the build step there
  #     concurrency:
  # group: ${{ github.ref }}
  # cancel-in-progress: truecon

  # TODO: Do we want to do a Prisma migrate here?
  # The major requirement is that this migration MUST occur before Nextjs tried to build.
  # migrate-db:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Migrate database
  #       env:
  #         DATABASE_URL: ${{ secrets.STAGE_DATABASE_URL }}
  #       run: |
  #         cd nextjs/prisma
  #         npx prisma migrate deploy

  create-stage:
    # needs: migrate-db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pulumi dependencies
        working-directory: .pulumi
        run: npm install

      - name: Create resources
        uses: pulumi/actions@v3
        with:
          work-dir: ./.pulumi
          command: up
          stack-name: stage
          commment-on-pr: true
          edit-pr-comment: true
          github-token: ${{secrets.GITHUB_TOKEN}}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}

  # e2e:
  #   concurrency:
  #     group: ${{ github.ref }}
  #     cancel-in-progress: true
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         working-directory: ./lib/e2e
  #         config-file: config.ci.json
