# You may not want to tear down your staging environment when you attempt to deploy to production.
# Other options:
# You could choose to never tear it down if you are willing to pay for it to continue to run.
# You could manually tear it down either using your Pulumi CLI or using this workflow with a manual trigger.
# You could tear down after a successful deployment to production.
name: Tear Down Stage

on:
  push:
    branches:
      - master

jobs:
  destroy-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pulumi dependencies
        uses: pulumi/actions@v3
        with:
          work-dir: ./.pulumi
          command: destroy
          stack-name: stage
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{secrets.DIGITALOCEAN_TOKEN}}
